// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ADO_WPFSH.Models;

[Table("Education")]
public partial class Education
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(35)]
    [Unicode(false)]
    public string Name { get; set; }
}