// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ADO_WPFSH.Models;

[Table("Employee")]
public partial class Employee
{
    [Key]
    public int Tab { get; set; }

    [Required]
    [StringLength(25)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(25)]
    [Unicode(false)]
    public string SecondName { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string ParentName { get; set; }

    public bool? Gender { get; set; }

    public DateOnly? BirthDate { get; set; }

    public int? CountryId { get; set; }

    public int? RegionCode { get; set; }

    public int? QualifyId { get; set; }

    public int? EducationId { get; set; }
}