// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ADO_WPFSH.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ADO_WPFSH.Models
{
    public partial interface IAnketaContextProcedures
    {
        Task<List<RegionNameResult>> RegionNameAsync(string reg, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
