// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ADO_WPFSH.Models;

[Table("Qualify")]
public partial class Qualify
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(25)]
    [Unicode(false)]
    public string Number { get; set; }
}