// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ADO_WPFSH.Models
{
    public partial class RegionNameResult
    {
        [StringLength(25)]
        public string SecondName { get; set; }
    }
}
