// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ADO_WPFSH.Models;

[Keyless]
[Table("Region")]
public partial class Region
{
    public int? Code { get; set; }

    [Required]
    [StringLength(55)]
    public string Name { get; set; }

    public int? CountryId { get; set; }
}